var colorBlueZone='#042084';
var colorGreenZone='#007527';
var colorRedZone='#FF0012';

var colorBlueZoneHover='#84C8EF';
var colorGreenZoneHover='#C8E6C9';
var colorRedZoneHover='#E57373';

var downColor='#F0F4C3';

var map_config = {
	'default':{
		'borderColor':'#9CA8B6', //inter-state borders
		'lakesColor':'#ACE9FC', // lakes color
		'namesColor':'#fff', //color of short names
		'mapShadow':'#000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'hoverShadow':'#666666', //tooltip shadow color
	},
	/*BlueZone*/
	'map_1':{
		'hover': 'Patient First | P: (703) 357-9707 | 2199 OLD BRIDGE RD.', //state hover content
		'url':'', //Goto URL
		'target':'same_window', //open link in new window:new_window, open in current window:same_window, or none for nothing.
		'upColor':colorBlueZone, //state's color when page loads
		'overColor':colorBlueZoneHover, //state's color when mouse hover
		'downColor':downColor,//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'hover': 'Dunkin Donuts | (703) 490-5135 | 2201 OLD BRIDGE RD..', 
		'url':'', 
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_3':{
		'hover': ' Safeway | P: (703) 494-8858 | 2205 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_4':{
		'hover': 'Layla’s Lebanese Restaurant | P: (703) 492-1500 | 2217 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_5':{
		'hover': 'Massage | P: (703) 497-5567 | 2219 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_6':{
		'hover': 'Edgemoor Art Studio | P: (703) 490-2355| 2221 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_7':{
		'hover': 'Curves | P: (703) 497-4244 | 2223 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_8':{
		'hover': 'Virginia ABC | P: (703) 494-0329 | 2225 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_9':{
		'hover': 'Classic Travel | P: (703) 494-2882 | 2227 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_10':{
		'hover': 'Lake Ridge Pizzeria | P: (703) 494-2134 | 2229 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_11':{
		'hover': 'NT Salon | P: (703) 492-935 | 2231 OLD BRIDGE DR.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_12':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_13':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_14':{
		'hover': 'Woodbridge Academy of Dance | P: (703) 583-2623 | 2235 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_15':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_16':{
		'hover': 'Lake Ridge Library | P: (703) 792-5675 | 2239 OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_17':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_18':{
		'hover': '9Round Kickboxing | P: (866) 619-797 | 2243C OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_19':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_20':{
		'hover': 'PenFed Realty | P: (703) 897-4663 | 2253A OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_21':{
		'hover': 'Lake Ridge Florist / Boomers | P: (703) 494-2299 | 2253B OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_22':{
		'hover': 'May, Hettler, and Assoc. Optometrists | P: (703) 494-8900 | 2253C OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_23':{
		'hover': 'Statements The Salon | P: (703) 494-2400 | 2253D OLD BRIDGE RD.',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_24':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_25':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window', 
		'upColor':colorBlueZone,
		'overColor':colorBlueZoneHover, 
		'downColor':downColor,
		'enable':true,
	},

	/*BlueZone END*/

	/*GreenZone*/

	'map_26':{
		'hover': 'Polaris Press | P: (703) 680-6060 | 2212 TACKETTS MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_27':{
		'hover': 'Kumon Learning Center | P: (703) 492-0690| 2214 TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_28':{
		'hover': 'The Arc | P: (703) 670-4800 | 2216 TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_29':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_30':{
		'hover': 'RGS Title | P: (703) 491-9600 | 2220 TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_31':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_32':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_33':{
		'hover': 'Clearbrook Center of the Arts | P: (703) 491-2611 | 2230B TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_34':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_35':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_37':{
		'hover': 'Pet Value | P: (571) 408-4129 | 2233 OLD BRIDGE DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_36':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':false,
	},
	'map_38':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_39':{
		'hover': 'Pediatric Achievements | P: (703) 491-1044 | 2239 C/D TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_40':{
		'hover': 'Pediatric Achievements | P: (703) 491-1044 | 2239 C/D TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_41':{
		'hover': 'RDT, INC. | P: (703) 499-9188 | 2235B TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_42':{
		'hover': 'Slender Spa | P: (703) 490-6667 | 2235A TACKETT1S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_43':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_44':{
		'hover': 'State Farm | P: (703) 490-6324 | 2237C TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorGreenZone,
		'overColor':colorGreenZoneHover, 
		'downColor':downColor,
		'enable':true,
	},

	/*GreenZone END*/

	/*RedZone*/

	'map_45':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_46':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_47':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_48':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_49':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_50':{
		'hover': 'After the Fall | P: (703) 497-0333 | 2239K TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_51':{
		'hover': 'Joel R. Braunfeld, DDS | P: (703) 491-2200 | 2239L TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_52':{
		'hover': 'Kite Architecture | P: (703) 492-2002 | 2239M TACKETT1S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_53':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_54':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_55':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_56':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_57':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_58':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_59':{
		'hover': 'Occoquan Supervisor | 2241K TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_60':{
		'hover': 'Jenn Elisabeth Studios | 2241H TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_61':{
		'hover': 'Benjamin`s Counseling | P: (703) 494-1434 | 2241G TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_62':{
		'hover': 'Prince William Conservation Alliance | P: (703) 459-4954 | 2241F TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_63':{
		'hover': 'VA State Referee Program | P: (703) 491-1717 | 2241E TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_64':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_65':{
		'hover': 'Congressman Gerry Connolly | P: (571) 408-4407 | 2241D TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_66':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_67':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_68':{
		'hover': 'Panda Chinese | P: (703) 497-6688 | 2241A TACKETT`S MILL DR.',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_69':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	},
	'map_70':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':false,
	},
	'map_71':{
		'hover': 'VACANT',
		'url':'',
		'target':'same_window',
		'upColor':colorRedZone,
		'overColor':colorRedZoneHover, 
		'downColor':downColor,
		'enable':true,
	}
}
